### ISSUE TITLE
Input shape mismatching of Kitchen environment

### ISSUE THREAD

**Issue by ka2hyeon** [artberryx/CSD-public#4]
Thank you for impressive research.
I want to reproduce your result in the kitchen example.
However, when I follow your kitchen example,
```
python train.py --run_group Exp --env_name Kitchen --n_epochs 502 --num_cpu 1 --logging True --note DIAYN --hidden 256 --layers 2 --skill_type continuous --num_skills 2 --n_cycles 40 --policy_save_interval 500 --plot_freq 25 --plot_repeats 4 --max_path_length 50 --n_batches 10 --rollout_batch_size 2 --sk_clip 0 --et_clip 1 --seed 0 --buffer_size 100000 --polyak 0.995 --n_random_trajectories 50 --algo_name csd --inner 1 --algo csd --dual_reg 1 --dual_lam_opt adam --dual_dist s2_from_s --dual_init_lambda 3000 --dual_slack 1e-06 --train_start_epoch 50 --sk_r_scale 500 --et_r_scale 0.02
```

I got a following error:
```
Traceback (most recent call last):
  File "train.py", line 606, in <module>
    main()
  File "/home/robot/miniconda3/envs/csd/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/robot/miniconda3/envs/csd/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/robot/miniconda3/envs/csd/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/robot/miniconda3/envs/csd/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "train.py", line 603, in main
    launch(**kwargs)
  File "train.py", line 478, in launch
    params = config.prepare_params(params)
  File "/home/robot/ws/jh_raph.park/CSD-public/baselines/her/experiment/config.py", line 115, in prepare_params
    tmp_env = cached_make_env(kwargs['make_env'])
  File "/home/robot/ws/jh_raph.park/CSD-public/baselines/her/experiment/config.py", line 88, in cached_make_env
    env = make_env()
  File "/home/robot/ws/jh_raph.park/CSD-public/baselines/her/experiment/config.py", line 105, in make_env
    env = KitchenMicrowaveKettleLightTopLeftBurnerV0Custom(control_mode='end_effector')
  File "/home/robot/ws/jh_raph.park/CSD-public/d4rl_alt/kitchen/kitchen_envs.py", line 216, in __init__
    super().__init__(*args, **kwargs)
  File "/home/robot/ws/jh_raph.park/CSD-public/d4rl_alt/kitchen/kitchen_envs.py", line 42, in __init__
    super(KitchenBase, self).__init__(**kwargs)
  File "/home/robot/ws/jh_raph.park/CSD-public/d4rl_alt/kitchen/adept_envs/franka/kitchen_multitask_v0.py", line 945, in __init__
    super(KitchenTaskRelaxV1, self).__init__(**kwargs)
  File "/home/robot/ws/jh_raph.park/CSD-public/d4rl_alt/kitchen/adept_envs/franka/kitchen_multitask_v0.py", line 194, in __init__
    self.reset_mocap_welds(self.sim)
  File "/home/robot/ws/jh_raph.park/CSD-public/d4rl_alt/kitchen/adept_envs/franka/kitchen_multitask_v0.py", line 364, in reset_mocap_welds
    sim.model.eq_data[i, :] = np.array(
ValueError: could not broadcast input array from shape (7) into shape (11)

```

**Comment by seohongpark** [comment]
Thank you for your interest in our work. This is likely due to the version mismatch. Please check whether your `dm-control`, `mujoco`, and `mujoco-py` packages have the correct versions as specified in `requirements.txt`.
